"""
Django settings for tic_tac_toe project.

Generated by 'django-admin startproject' using Django 4.1.2.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-5-g=6(fycy7r5=h0z9$3ldhbg509rtb%i%t6-#2zwlua_(in%i",
)

# DEBUG and ALLOWED_HOSTS configurable via env (Render ke liye useful)
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ["true", "1", "t"]
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")

# ============================
# Application definition
# ============================

INSTALLED_APPS = [
    # "channels",  # Channels ko hata diya deployment error avoid karne ke liye
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "game",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tic_tac_toe.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Normal WSGI app (gunicorn ke saath)
WSGI_APPLICATION = "tic_tac_toe.wsgi.application"
# ASGI_APPLICATION = "tic_tac_toe.asgi.application"  # Abhi ki deploy ke liye zaroori nahi

# ============================
# Database
# ============================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ============================
# Password validation
# ============================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ============================
# Internationalization
# ============================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ============================
# Static files
# ============================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ============================
# Default PK field
# ============================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Channels config hata diya (InMemoryChannelLayer, etc.)
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     },
# }
